
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Engine-less client (NETLIFY-MIGRATION-PLAN.md §0.2, proven in Phase 0): the app
  // always connects through a driver adapter (PrismaLibSql for Turso, better-sqlite3
  // locally — see db.ts), so no Rust query-engine binary is needed. This drops the
  // .node binary that otherwise won't bundle into a Netlify Function (risks R4/R7).
  // Runtime-equivalent on Vercel/local (same adapter query path); the generated
  // client is gitignored and regenerated per build, so this is parallel-run safe.
  engine: "client",
  datasource: {
    url: env("DATABASE_URL"),
  },
  seed: {
    command: "ts-node-dev prisma/seed.ts",
  },
});
